<?php
define('ORIGINAL_POST_TYPE','originals');

define('ORIGINAL_POST_TYPE_LABEL','Originals');
define('ORIGINAL_POST_TYPE_LABEL_SINGULAR','Original');

define('ORIGINAL_MAX_ARTICLE_CONTENT_LENGTH',255);
define('PAGINATION_ORIGINAL_PAGE',30);
define('NO_OF_COL_ORIGINAL_PAGE',3);

//Pages Titles
define('PAGE_TITLE_ORIGINAL_ARTIST','Original');
define('ORIGINAL_MENU_TITLE','artist_menu');
define('ORIGINAL_QUERY_VAR_ARTISTSLUG','artistslug');
define('ORIGINAL_CURRENCY','€');

define('ORIGINAL_ADMIN_COLUMN_TITLE','Title');
define('ORIGINAL_ADMIN_COLUMN_CATEGORY','Categories');

define('ORIGINAL_METABOX_HEADER_CREATION_YEAR','Creation Year');
define('ORIGINAL_METABOX_HEADER_MARKS','Marks');
define('ORIGINAL_METABOX_HEADER_MEDIUM','Medium');
define('ORIGINAL_METABOX_HEADER_ARTIST','Artist');
define('ORIGINAL_METABOX_HEADER_DIMENSIONS','Dimensions');
define('ORIGINAL_METABOX_HEADER_AUCTION','Auction');

define('ORIGINAL_METABOX_LABEL_DIMENSIONS','Dimensions');

define('ORIGINAL_METABOX_DIMENSIONS_CENTIMETER_FULL','centimeter');
define('ORIGINAL_METABOX_DIMENSIONS_CENTIMETER_SHORT','cm');

define('ORIGINAL_METABOX_DIMENSIONS_INCHES_FULL','inches');
define('ORIGINAL_METABOX_DIMENSIONS_INCHES_SHORT','in');

define('ORIGINAL_METABOX_CREATION_YEAR_LABEL','Creation Year');
define('ORIGINAL_METABOX_ARTIST_LABEL','Artist');
define('ORIGINAL_METABOX_MARKS_LABEL','Marks');
define('ORIGINAL_METABOX_MEDIUM_LABEL','Medium');

define('ORIGINAL_METABOX_AUCTION_HAMMER_PRICE_LABEL','Hammer Price');
define('ORIGINAL_METABOX_AUCTION_LOW_ESTIMATE_LABEL','Low Estimate');
define('ORIGINAL_METABOX_AUCTION_HIGH_ESTIMATE_LABEL','High Estimate');
define('ORIGINAL_METABOX_AUCTION_SALES_DATE_LABEL','Sales Date');
define('ORIGINAL_METABOX_AUCTION_AUCTION_HOUSE_LABEL','Auction House');
define('ORIGINAL_METABOX_AUCTION_LOT_NUMBER_LABEL','Lot Number');
define('ORIGINAL_METABOX_AUCTION_CATEGORY_LABEL','Category');

define('ORIGINAL_BUTTON_ADD_NEW_AUCTION',' + Add New Auction');

define('ORIGINAL_METABOX_HEADER_DETAIL_AUCTION','Auction');

define('ORIGINAL_MESSAGE_NO_POSTS','Sorry, no posts matched your criteria.');